### ISSUE TITLE
`pnpm check` is very unhappy

### ISSUE THREAD

**Issue by ollema** [ollema/mikrofabriken_portal#23]
not sure what caused this, but for some reason `pnpm check` which runs type checks is really unhappy after the latest couple of changes.

```bash
> pnpm check
svelte-check found 91 errors and 0 warnings in 22 files
```

we should try to fix these so that we can add the following job to the CI workflow:
```yaml
  check:
    name: Check
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm check

```
